language: node_js
cache: npm
notifications:
  email: false
node_js:
  # technically we support 10.0.0, but some of our tooling doesn't
  - 10.14.2
  - 12
  - 14
  - node
env:
  - REACT_NEXT=false
  - REACT_NEXT=true
install:
  - npm install
  # as requested by the React team :)
  # https://reactjs.org/blog/2019/10/22/react-release-channels.html#using-the-next-channel-for-integration-testing
  - if [ "$REACT_NEXT" = true ]; then npm install react@next
    react-dom@next; fi
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta

jobs:
  allow_failures:
    - env: REACT_NEXT=true
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
