language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 10.0.0
  - 12
  - node
install:
  - npm install
  # as requested by the React team :)
  # https://reactjs.org/blog/2019/10/22/react-release-channels.html#using-the-next-channel-for-integration-testing
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then npm install react@next
    react-dom@next; fi
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta

jobs:
  include:
    - stage: release
      node_js: 12
      script: kcd-scripts travis-release
      if: fork = false
