language: node_js
cache: npm
notifications:
  email: false
node_js:
  # technically we support 10.0.0, but some of our tooling doesn't
  - 10.14.2
  - 12
  - 14
  - 15
env:
  - REACT_DIST=latest
  - REACT_DIST=next
  - REACT_DIST=experimental
  # node15 compat
  # Revisit once https://github.com/npm/cli/pull/2047 is released.
  - npm_config_yes=true
env:
  - REACT_DIST=latest
  - REACT_DIST=next
  - REACT_DIST=experimental
install:
  - npm install
  # as requested by the React team :)
  # https://reactjs.org/blog/2019/10/22/react-release-channels.html#using-the-next-channel-for-integration-testing
  - npm install react@$REACT_DIST react-dom@$REACT_DIST
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta

jobs:
  allow_failures:
    - REACT_DIST=next
    - REACT_DIST=experimental
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
